<?PHP
define('ROOT_PATH','/var/www/html/bs4');
define('LIBS_PATH',ROOT_PATH.'/libs');
define('CLASS_PATH',ROOT_PATH.'/class');
define('HOST_PATH',ROOT_PATH.'/hosts');
define('LANGUAGES_PATH',ROOT_PATH.'/languages');
define('GA_PATH',ROOT_PATH.'/ga');
define('CSS_PATH',ROOT_PATH.'/hosts');
define('JSON_PATH',ROOT_PATH.'/hosts');
define('PLUGIN_PATH',ROOT_PATH.'/plugin');
define('WORK_PATH',ROOT_PATH.'/work');
define('DATA_SOURCE_PATH',WEB_URL.'/api/');
define('VIEW_PATH',ROOT_PATH.'/view/');
define('MODULE_PATH',ROOT_PATH.'/module/');
define('ECOCAT_PATH','/ecocat'.ECOCAT_VERSION);
define('ECOCAT_ROOT',ROOT_PATH.'/ecocatcms'.ECOCAT_VERSION);
define('FILE_UPLOAD_PATH','uploadfiles/');
define('LOG_DIR','/var/www/html/logs/');
define('FILE_PATH',ROOT_PATH.'/files');
define('CACHE_PATH',ROOT_PATH.'/cache');
?>
